In [1]:
import numpy as np 

# Operations on Array `

In [4]:
a = np.arange(1,16,1)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [5]:
a>10 

array([False, False, False, False, False, False, False, False, False,
       False,  True,  True,  True,  True,  True])

In [7]:
b = a>10 
a[b]

array([11, 12, 13, 14, 15])

In [9]:
a[a%2==0] 

array([ 2,  4,  6,  8, 10, 12, 14])

In [10]:
a[a%2!=0]

array([ 1,  3,  5,  7,  9, 11, 13, 15])

In [11]:
a = np.arange(1,5)
a

array([1, 2, 3, 4])

# Reshaping the Array

n(rows)*n(columns) = total_elements

In [19]:
a = np.arange(1,13)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [20]:
a.shape

(12,)

In [21]:
# 1*12 , 12*1 
# 2*6 , 6*2 
# 3*4 , 4*3 

In [22]:
a.reshape(2,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [23]:
a.reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [24]:
a.reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [25]:
a.reshape(5,3)

ValueError: cannot reshape array of size 12 into shape (5,3)

In [29]:
a = np.arange(1,5).reshape(2,2)
a

array([[1, 2],
       [3, 4]])

In [31]:
b = np.arange(5,9).reshape(2,2)
b

array([[5, 6],
       [7, 8]])

In [32]:
a+b  ### (1+5 = 6 , 2+6 = 8 , 3+7=10 , 4+8 = 12)

array([[ 6,  8],
       [10, 12]])

In [33]:
a-b

array([[-4, -4],
       [-4, -4]])

In [34]:
a*b

array([[ 5, 12],
       [21, 32]])

In [35]:
a.dot(b)    ## for matrix multiplication 

array([[19, 22],
       [43, 50]])

In [36]:
a/b

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [37]:
a

array([[1, 2],
       [3, 4]])

In [38]:
a**2

array([[ 1,  4],
       [ 9, 16]])

In [41]:
a**3

array([[ 1,  8],
       [27, 64]], dtype=int32)

In [42]:
# LinSpace() ----> It will return same gap values in a given range . 

In [43]:
a = np.linspace(1,2,5)
a

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

In [44]:
# 1.25-1 = 0.25 
# 1.5-1.25 = 0.25
# 1.75-.1.50 = 0.25 
# 2-1.75 = 0.25

In [45]:
# unique() ----> It will provide an array in which it will return 3 array . 
# arr ---> return unique values 
# return_index = True ----> return indexing of unique values . 
# return_counts = True ----> return frequrncy of each unique values . 

In [46]:
a = np.array([1,2,3,1,1,1,2,6,7])
a

array([1, 2, 3, 1, 1, 1, 2, 6, 7])

In [47]:
np.unique(a , return_index=True , return_counts=True) 

(array([1, 2, 3, 6, 7]),
 array([0, 1, 2, 7, 8], dtype=int64),
 array([4, 2, 1, 1, 1], dtype=int64))

In [48]:
a = np.arange(1,10).reshape(3,3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [49]:
np.sum(a) 

45

In [50]:
1+2+3+4+5+6+7+8+9

45

In [51]:
np.sum(a , axis = 0)   ### returns column wise sum 

array([12, 15, 18])

In [52]:
np.sum(a , axis = 1)   ### return row wise sum 

array([ 6, 15, 24])

# hstack and vstack

In [54]:
a = np.arange(1,5)
b = np.arange(5,9)
c = np.arange(9,13)

In [55]:
np.hstack((a,b,c))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [56]:
np.vstack((a,b,c))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [57]:
a = np.arange(1,5)
a

array([1, 2, 3, 4])

In [58]:
np.sqrt(a) 

array([1.        , 1.41421356, 1.73205081, 2.        ])

In [59]:
np.sin(a) 

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [60]:
np.cos(a) 

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])